<?php

namespace AppBundle\Repository;

/**
 * ForeverPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForeverPackRepository extends \Doctrine\ORM\EntityRepository
{
}
