<?php

namespace AppBundle\Repository;

/**
 * ForeverPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForeverPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
