<?php

namespace AppBundle\Repository;

/**
 * MatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
