<?php

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;

use AppBundle\Entity\Matrice;
use AppBundle\Entity\Membre;

/**
 * MatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceRepository extends \Doctrine\ORM\EntityRepository
{

	public function addWhereClause(&$qb,&$params){

        $params = array_filter($params,function($el){
            if(is_array($el)){
                return $el;
            }
            return strip_tags(trim($el));
        });

		// recherche par terms
		if(@$params["q"]){
			$this->whereTerms($qb,@$params["q"]);
		}

		// recherche par id
		if(@$params["id"]){
			$this->whereId($qb,@$params["id"]);
		}

		// recherche par membre_id
		if(@$params["membre_id"]){
			$this->whereMembreId($qb,@$params["membre_id"]);
		}

		// recherche des feuilles
		if(@$params["is_leaft"]){
			$this->whereIsLeaft($qb);
		}
		// recherche des noeuds
		if(@$params["is_node"]){
			$this->whereIsNode($qb);
		}
		// recherche la racine
		if(@$params["is_root"]){
			$this->whereIsRoot($qb);
		}
		// recherche les parents hiérachique d'une reference
		if(@$params["is_reference_parent"]){
			$this->whereIsReferenceParent($qb,@$params["ref_left"],@$params["ref_right"]);
		}
		// recherche tous les éléments indépendants d'un élément de référence
		if(@$params["is_not_under_reference"]){
			$this->whereIsNotUnderAReference($qb,@$params["ref_left"],@$params["ref_right"]);
		}
		// recherche tous les éléments sous une référence
		if(@$params["is_under_reference"]){
			$this->whereIsUnderAReference($qb,@$params["ref_left"],@$params["ref_right"],$params);
		}


		// recherche par indice
		// recherche tous les éléments sous une référence y compris la reference
        if(@$params["left_ind"] && @$params["right_ind"]){
            $this->whereRangeIndice($qb,$params["left_ind"],$params["right_ind"]);
        }
        else if(@$params["left_ind"]){
            $this->whereLeftIndice($qb,$params["left_ind"]);
        }
        else if(@$params["right_ind"]){
            $this->whereRightIndice($qb,$params["whereRightInd"]);
        }

        // recherche par profondeur
        if(@$params["depth"] && @$params["depth_end"]){
            $this->whereRangeDepth($qb,$params["depth"],$params["depth_end"]);
        }
        else if(@$params["depth"]){
            $this->whereDepth($qb,$params["depth"]);
        }

        return $this;
    }


	/**
	 * permet de retourner tous les elements de l'arbre
	 * 
	 * @param array $params les pararatres de la recherche
	 * @param integer $limit le nombre de resultat à retourner
	 * @param integer $offset la position de bebut de cette recherche
	 */
	public function search($params = array(),$limit = 50,$offset=0){
		$qb = $this->createQueryBuilder("m")
		->leftJoin("m.membre","membre");

		$this->addWhereClause($qb,$params);

		if(!@$params['order_id']){
    		$params["order_id"] = "asc";
    	}

		// ordre d'affichage par id
        if(@$params['order_id']){
            $order = strtoupper(trim($params['order_id'])) == "ASC" ? "ASC" : "DESC";
            $qb->orderBy("m.leftInd",$order);
        }

	    // limit et offset
	    $qb->setFirstResult( $offset )
   		->setMaxResults( $limit );

   		$query = $qb->getQuery();

	    return $query->getResult();
	}


	/**
	* Permet l'insertion d'une feuille dans l'arbre sous une reference
	* 
	* @param \AppBundle\Entity\Membre 	$adherent le membre à positionner
	* @param  AppBundle\Entity\Matrice  $reference la reference
	* @return void
	*/
	public function InsertLeaft(Membre &$adherent, Matrice &$reference){

		$steper = $reference->getRightInd() - $reference->getLeftInd();

		//var_dump($reference->getMembre()->getUsername().' :['.$reference->getLeftInd().','.$reference->getRightInd().']');

		/*UPDATE NEW_FAMILLE
		SET NFM_BD = NFM_BD + 2
		WHERE NFM_BD >= 35*/

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.rightInd","m.rightInd + 2")
		->where($qb->expr()->gte("m.rightInd",":ref_right"))
		->setParameter("ref_right",$reference->getRightInd())
		->getQuery();
		$p = $q->execute();

		/*UPDATE NEW_FAMILLE
		SET NFM_BG = NFM_BG + 2
		WHERE NFM_BG >= 35*/

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.leftInd","m.leftInd + 2")
		->where($qb->expr()->gte("m.leftInd",":ref_right"))
		->setParameter("ref_right",$reference->getRightInd())
		->getQuery();
		$p = $q->execute();


		/*INSERT INTO NEW_FAMILLE (NFM_BG, NFM_BD, NFM_LIB)
   		VALUES (35, 36, 'Roller')*/

   		$item = new Matrice();
		$item->setMembre($adherent);
		$item->setLeftInd($reference->getRightInd());
		$item->setRightInd($reference->getRightInd() + 1);
		$item->setDepth($reference->getDepth() +1 );

		if($steper > 1){

		}
		$this->_em->persist($item);
		$this->_em->refresh($reference);
	}

	/**
	* Permet la supression d'une reference dans l'arbre
	* 
	* @param  AppBundle\Entity\Matrice  $reference la reference à supprimer
	* @return void
	*/
	public function removeNode(Matrice &$reference){

		$steper = intval($reference->getRightInd()) - intval($reference->getLeftInd()) + 1;

		// DELETE FROM NEW_FAMILLE
		// WHERE  NFM_BG >= 22 AND NFM_BD <= 35

		$qb = $this->createQueryBuilder("m");
		$q = $qb->delete()
		->where($qb->expr()->andX(
			$qb->expr()->gte("m.leftInd",":ref_left"),
			$qb->expr()->lte("m.rightInd",":ref_right")
		))
		->setParameter("ref_left",$reference->getLeftInd())
		->setParameter("ref_right",$reference->getRightInd())
		->getQuery();
		$p = $q->execute();


		// UPDATE NEW_FAMILLE
		// SET NFM_BG = NFM_BG - 14
		// WHERE NFM_BG > 22

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.leftInd","m.leftInd - :steper")
		->where($qb->expr()->gt("m.leftInd",":ref_left"))
		->setParameter("ref_left",$reference->getLeftInd())
		->getQuery();
		$p = $q->execute();


		// UPDATE NEW_FAMILLE
		// SET NFM_BD = NFM_BD - 14
		// WHERE NFM_BD >= 22

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.rightInd","m.rightInd - :steper")
		->where($qb->expr()->gte("m.rightInd",":ref_left"))
		->setParameter("ref_left",$reference->getLeftInd())
		->getQuery();
		$p = $q->execute();

		$this->_em->refresh($reference);
	}

	/**
	* Permet l'insertion d'un noeud  sous une reference
	* 
	* @param  AppBundle\Entity\Matrice  $node le noeud à ajouter
	* @param  AppBundle\Entity\Matrice  $reference la reference sous laquelle ajouter
	* @return void
	*/
	public function insertNode(Matrice &$node,Matrice &$reference){

		$steper = intval($node->getRightInd()) - intval($node->getLeftInd()) + 1;

		/*UPDATE NEW_FAMILLE
		SET NFM_BD = NFM_BD + stepper
		WHERE NFM_BD >= 35*/

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.rightInd","m.rightInd + :steper")
		->where($qb->expr()->gte("m.rightInd",":ref_right"))
		->setParameter("ref_right",$reference->getRightInd())
		->setParameter("steper",$steper)
		->getQuery();
		$p = $q->execute();

		/*UPDATE NEW_FAMILLE
		SET NFM_BG = NFM_BG + stepper
		WHERE NFM_BG >= 35*/

		$qb = $this->createQueryBuilder("m");
		$q = $qb->update()
		->set("m.leftInd","m.leftInd + :steper")
		->where($qb->expr()->gte("m.leftInd",":ref_right"))
		->setParameter("ref_right",$reference->getRightInd())
		->setParameter("steper",$steper)
		->getQuery();
		$p = $q->execute();

		/*INSERT INTO NEW_FAMILLE (NFM_BG, NFM_BD, NFM_LIB)
   		VALUES (35, 36, 'Roller')*/


		$node->setLeftInd($reference->getRightInd());
		$node->setRightInd($reference->getRightInd() + $steper - 1);
		$node->setDepth($reference->getDepth() +1 );


		/*SELECT node.name, (COUNT(parent.name) - 1) AS depth
		FROM nested_category AS node,
		        nested_category AS parent
		WHERE node.lft BETWEEN parent.lft AND parent.rgt
		GROUP BY node.name
		ORDER BY node.lft;*/

		// mise a jour de la profondeur en dessous du noeud
		$qb = $this->createQueryBuilder("m")
		->join("AppBundle\\Entity\\Matrice","p");

		$q = $qb->update()
		->set("m.depth",$qb->expr()->count('p.membre_id') - 1)
		->where($qb->expr()->andX(
			$qb->expr()->andX(
				$qb->expr()->gt("m.leftInd",":ref_left"),
				$qb->expr()->lt("m.rightInd",":ref_right"),
				$qb->expr()->between("m.leftInd","p.leftInd","p.rightInd")
			)
		))
		->groupBy("m.membre_id")
		->setParameter("ref_left",$node->getLeftInd())
		->setParameter("ref_right",$node->getRightInd())
		->getQuery();
		$p = $q->execute();

		$this->_em->refresh($reference);
	}

	

	public function whereTerms(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->orX(
			$qb->expr()->like("m.username", ":q"),
			$qb->expr()->like("m.email", ":q")
		))
	    ->setParameter("q","%$value%");
	}

	public function whereId(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->eq("m.id", ":id"))
	    ->setParameter("id",$value);
	}

	public function whereMembreId(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->eq("membre.id", ":membre_id"))
	    ->setParameter("membre_id",$value);
	}

	public function whereLeftInd(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->eq("m.leftInd", ":left_ind"))
	    ->setParameter("left_ind",$value);
	}

	public function whereRightInd(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->eq("m.rightInd", ":right_ind"))
	    ->setParameter("right_ind",$value);
	}

	/**
	* recherche tous les éléments sous une référence y compris la reference
	* 
	* @param  QueryBuilder $qb  
	* @param  integer       $leftInd l'indice gauche de la reference
	* @param  integer       $rightInd   l'indice droit de la reference
	* @return void
	*/
	public function whereRangeIndice(QueryBuilder $qb,$leftInd,$rightInd){
		$qb->andWhere(
			$qb->expr()->between("m.leftInd",":ref_left",":ref_right")
		)
        ->setParameter("ref_left",$leftInd)
        ->setParameter("ref_right",$rightInd);
  	}

  	public function whereDepth(QueryBuilder $qb,$value){
		$qb->andWhere($qb->expr()->eq("m.depth", ":depth"))
	    ->setParameter("depth",$value);
	}

	public function whereRangeDepth(QueryBuilder $qb,$start,$end){
		$qb->andWhere(
			$qb->expr()->between("m.depth",":depth_start",":depth_end")
		)
        ->setParameter("depth_start",$start)
        ->setParameter("depth_end",$end);
  	}

  	/**
  	* Recherche les feuilles de l'arbre
  	* @param  QueryBuilder $qb
  	* @return void
  	*/
  	public function whereIsLeaft(QueryBuilder $qb){
		$qb->andWhere(
			$qb->expr()->eq("m.leftInd","m.rightInd - 1")
		);
  	}

  	/**
  	* Recherche les noeuds de l'arbre
  	* @param  QueryBuilder $qb
  	* @return void
  	*/
  	public function whereIsNode(QueryBuilder $qb){
		$qb->andWhere(
			$qb->expr()->not($qb->expr()->eq("m.leftInd","m.rightInd - 1"))
		);
  	}

  	/**
  	* Recherche la racine de l'arbre
  	* @param  QueryBuilder $qb
  	* @return void
  	*/
  	public function whereIsRoot(QueryBuilder $qb){
		$qb->andWhere(
			$qb->expr()->eq("m.leftInd",1)
		);
  	}

  	/**
	* permet de retrouver tous les parents hierachique d'une reference
	* 
	* @param integer $leftInd l'index gauche de la reference
	* @param integer $rightInd l'index droit de la reference
	*/
	public function whereIsReferenceParent(QueryBuilder $qb,$leftInd,$rightInd){
		$qb
		->andWhere($qb->expr()->andX(
			$qb->expr()->lt("m.leftInd", ":ref_left"),
			$qb->expr()->gt("m.rightInd", ":ref_right")
		))
		->setParameter("ref_left",$leftInd)
		->setParameter("ref_right",$rightInd);
	}

	/**
	* permet de retourner tous les elements de l'arbre
	* sauf ceux en dessous d'une reference donnnée
	* 
	* @param integer $leftInd l'index gauche de la reference
	* @param integer $rightInd l'index droit de la reference
	*/
	public function whereIsNotUnderAReference(QueryBuilder $qb,$leftInd,$rightInd){
		$qb
		->andWhere($qb->expr()->orX(
			$qb->expr()->lt("m.leftInd", ":ref_left"),
			$qb->expr()->gt("m.rightInd", ":ref_right")
		))
		->setParameter("ref_left",$leftInd)
		->setParameter("ref_right",$rightInd);
	}

	/**
	* permet de retourner tous les elements de l'arbre sous une reference
	* 
	* @param integer $leftInd l'index gauche de la reference
	* @param integer $rightInd l'index droit de la reference
	*/
	public function whereIsUnderAReference(QueryBuilder $qb,$leftInd,$rightInd,$params = array()){
		
		$qb
		->andWhere($qb->expr()->andX(
			$qb->expr()->gt("m.leftInd", ":ref_left"),
			$qb->expr()->lt("m.rightInd", ":ref_right")
		))
		->setParameter("ref_left",$leftInd)
		->setParameter("ref_right",$rightInd);

		if(@$params['is_indirect_child']){
			$qb
			->andWhere($qb->expr()->gt("m.depth", ":ref_depth"))
			->setParameter("ref_depth",$params['ref_depth']);
		}

		if(@$params['is_direct_child']){
			$qb
			->andWhere($qb->expr()->eq("m.depth", ":ref_depth"))
			->setParameter("ref_depth",$params['ref_depth']);
		}
		
		if(@$params['is_node_child']){
			$qb->andWhere($qb->expr()->neq("m.leftInd", "m.rightInd - 1"));
		}

		if(@$params['is_leaft_child']){
			$qb->andWhere($qb->expr()->eq("m.leftInd", "m.rightInd - 1"));
		}

	}
	

	public function count(array $params = array() ){
        $qb = $this->createQueryBuilder('m')
        ->leftJoin("m.membre","membre");

        $qb
        ->select('count(m.id)');

        $this->addWhereClause($qb, $params);

        return $qb->getQuery()
        ->getSingleScalarResult();
    }

    public function generationCount(array $params = array() ){
        $qb = $this->createQueryBuilder('m')
        ->leftJoin("m.membre","membre");

        $qb
        ->select('max(m.depth)');

        $this->addWhereClause($qb, $params);

        return $qb->getQuery()
        ->getSingleScalarResult();
    }

    public function generateBonus(array $params = array() ){

		$em = $this->_em;

		$sql = "
			SELECT 
			SUM(
				(
					SELECT 
					SUM(
						cc.value * 
			    		(
			    			SELECT CASE 
			        		WHEN mt.code = 'NC'
			        		THEN
			        		(
			        			SELECT CASE 
								WHEN :current_user_type = 'M' 	THEN 0.18 
								WHEN :current_user_type = 'MA' 	THEN 0.13
								WHEN :current_user_type = 'A' 	THEN 0.08
								WHEN :current_user_type = 'AA' 	THEN 0.05
								ELSE 0
								END as etff
			        		)
			        		ELSE 0
			        		END as etf
			        	)
					)
					FROM  case_credit cc 
					WHERE 
					( 
						membre.id = cc.fbo_id 
					)
				)
			) as bonus_novus_customer,

			SUM( 
				(
					SELECT 
					SUM( 
			    		(
			    			SELECT CASE
			    			WHEN :current_user_type = 'M' 
			    			THEN
			    			(
				    			SELECT CASE 
				        		WHEN mt.code = 'MA' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.05)
				        			+
				        			(
					        			0.05 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		WHEN mt.code = 'A' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.1)
				        			+
				        			(
					        			0.1 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		WHEN mt.code = 'AA' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.13)
				        			+
				        			(
					        			0.13 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		ELSE 0
				        		END as etf
				        	)
				        	WHEN :current_user_type = 'MA' 
			    			THEN
			    			(
				    			SELECT CASE 
				        		WHEN mt.code = 'A' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.05)
				        			+
				        			(
					        			0.05 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		WHEN mt.code = 'AA' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.08)
				        			+
				        			(
					        			0.08 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		ELSE 0
				        		END as etf
				        	)
				        	WHEN :current_user_type = 'A' 
			    			THEN
			    			(
				    			SELECT CASE 
				        		WHEN mt.code = 'AA' AND m.depth = :current_user_depth + 1
				        		THEN
				        		(
				        			(cc.value * 0.03)
				        			+
				        			(
					        			0.03 * 

					        			(
					        				SELECT
					        				SUM(
					        					(
					        						SELECT 
					        						SUM(cc2.value)
					        						FROM  case_credit cc2 
													WHERE 
													( 
														m2.membre_id = cc2.fbo_id 
													)
					        					)
					        				)
					        				FROM matrice m2
											WHERE 
											(
												(m2.left_ind > m.left_ind AND m2.right_ind < m.right_ind)
											)
					        			)
					        		)
				        		)
				        		ELSE 0
				        		END as etf
				        	)
				        	ELSE 0
				        	END as oiu
			        	)
					)
					FROM  case_credit cc 
					WHERE 
					( 
						membre.id = cc.fbo_id 
					)
				)
			) as bonus_group

			FROM matrice m 
			INNER JOIN membre ON membre.id = m.membre_id
			INNER JOIN membre_type mt ON mt.id = membre.type_id
			LEFT JOIN corporation  ON corporation.id = membre.corporation_id
			LEFT JOIN membre parrain  ON parrain.id = membre.parrain_id
			WHERE 
			(
				(m.left_ind > :left_ind AND m.right_ind < :right_ind)
			)
		";

		$stmt = $em->getConnection()->prepare($sql);
    	$stmt->execute($params);
     
    	return $stmt->fetchAll()[0];
    }
}
