<?php

namespace AppBundle\Repository;

/**
 * MembreContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreContactRepository extends \Doctrine\ORM\EntityRepository
{
}
