<?php

namespace AppBundle\Repository;

/**
 * MembreRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
