<?php

namespace AppBundle\Repository;

/**
 * MembreTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
