<?php

namespace AppBundle\Repository;

/**
 * PercentagePerLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PercentagePerLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
