<?php

namespace AppBundle\Repository;

/**
 * PercentagePerMembreTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PercentagePerMembreTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
