<?php

namespace AppBundle\Repository;

/**
 * RemunerationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemunerationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
