<?php

namespace AppBundle\Repository;

/**
 * RemunerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemunerationRepository extends \Doctrine\ORM\EntityRepository
{
}
